# Personal data

name: Kara Longo      

email: klongo@epi.umaryland.edu

job_title: Program Director

degrees: ["MS"] # format degrees in quotes and separated by comma, ie: ["MS","Ph.D"]

institution_name: UMB

institution_URL: http://umaryland.edu 

department_name: DOM

department_URL: http://medschool.umaryland.edu

github_username: klongo

twitter_username: 

linkedin_URL: https://www.linkedin.com/pub/kara-longo/44/132/26b

selfie_URL: http://placehold.it/300x300


# Site data
markdown: kramdown
permalinks: pretty
